### PR TITLE
Disallow 0 amounts for transfer transactions - Closes #783

### LINKED ISSUE #783: Disallow 0 amounts for transfer transactions
### Expected behavior

Transfer transactions should not allow an amount of 0.

### Actual behavior

We don't have a special check for transfer transactions. Amount validation currently allows 0 for all transaction types.

### Steps to reproduce

Create a transfer transaction with amount 0 and try to broadcast it to the network.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0+

### PR DESCRIPTION
**Pull request by mitsujutsu**
### What was the problem?

Transfer transactions (type 0) should not allow an amount of 0.

### How did I fix it?

Add validator for transfer transaction amount. Enforce 0 amount for other transaction types in schema. 

### How to test it?

Create a transfer transaction with amount 0.

### Review checklist

* The PR resolves #783
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/utils/validation/validation.js [hunk 1]
```diff
@@ -83,6 +83,8 @@ export const validateAddress = address => {
 	return true;
 };
 
+export const isGreaterThanZero = amount => amount > 0;
```
Comment (shuse2) [inline packages/lisk-transactions/src/utils/validation/validation.js]: This would be `bignum` instance so it should compare using the bignum function

File: packages/lisk-transactions/test/utils/validation/validate_transaction.js [hunk 2]
```diff
@@ -54,7 +54,7 @@ describe('validateTransaction', () => {
 		describe('when the transaction contains invalid data in merged schema', () => {
 			const invalidTransaction = {
 				type: 0,
-				amount: '0',
+				amount: '1',
```
Comment (shuse2) [inline packages/lisk-transactions/test/utils/validation/validate_transaction.js]: Probably it's better to add `transferAmount` test here too, because it's also invalid merged schema pattern

File: packages/lisk-transactions/test/utils/validation/validator.js [hunk 3]
```diff
@@ -189,11 +189,55 @@ describe('validator', () => {
 		});
 
 		it('should validate to true when valid amount is provided', () => {
-			return expect(validate({ target: '190105310' })).to.be.true;
+			return expect(validate({ target: '0' })).to.be.true;
 		});
 
 		it('should validate to true when valid amount with leading zeros is provided', () => {
-			return expect(validate({ target: '00190105310' })).to.be.true;
+			return expect(validate({ target: '000000' })).to.be.true;
```
Comment (shuse2) [inline packages/lisk-transactions/test/utils/validation/validator.js]: I think target number should be non-zero value with leading zero

File: packages/lisk-transactions/test/utils/validation/validator.js [hunk 4]
```diff
@@ -189,11 +189,55 @@ describe('validator', () => {
...
+		});
+
+		it('should validate to true when valid amount is provided', () => {
+			return expect(validate({ target: '100' })).to.be.true;
 		});
 
 		it('should validate to true when valid amount with leading zeros is provided', () => {
-			return expect(validate({ target: '00190105310' })).to.be.true;
+			return expect(validate({ target: '000000100' })).to.be.true;
 		});
```
Comment (shuse2) [inline packages/lisk-transactions/test/utils/validation/validator.js]: Lets add `validate({ target: '0' }).to.be.false;`?
