### PR TITLE
Validate transaction inputs - Closes #752

### LINKED ISSUE #752: Validate transaction creator inputs
### Expected behavior

When attempting to create transactions with invalid inputs, the user should be informed which inputs are invalid and how. We should be able to use the new schema validation introduced in https://github.com/LiskHQ/lisk-elements/issues/734

### Actual behavior

We don't validate these inputs thoroughly.

### Steps to reproduce

Try to create a transfer transaction with a recipient ID that's out of range for example.

### Which version(s) does this affect? (Environment, OS, etc...)

1.1.0+

### PR DESCRIPTION
**Pull request by yatki**
### Review checklist

* The PR resolves #752 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/4_register_multisignature_account.js [hunk 1]
```diff
@@ -17,11 +17,28 @@ import {
...
 	validateKeysgroup,
 	wrapTransactionCreator,
+	isValidInteger,
 } from './utils';
 
-const registerMultisignatureAccount = ({ keysgroup, lifetime, minimum }) => {
+const validateInputs = ({ keysgroup, lifetime, minimum }) => {
 	validateKeysgroup(keysgroup);
 
+	if (!isValidInteger(lifetime) || lifetime < 1 || lifetime > 72) {
```
Comment (shuse2) [inline packages/lisk-transactions/src/4_register_multisignature_account.js]: It would be better to split this magic numbers in to some place.
In core, these are network `constants`

File: packages/lisk-transactions/src/4_register_multisignature_account.js [hunk 2]
```diff
@@ -17,11 +17,28 @@ import {
...
+		throw new Error(
+			'Please provide a valid lifetime value. Expected integer between 1 and 72.',
+		);
+	}
+
+	if (!isValidInteger(minimum) || minimum < 1 || minimum > 15) {
```
Comment (shuse2) [inline packages/lisk-transactions/src/4_register_multisignature_account.js]: Same as above

File: packages/lisk-transactions/src/0_transfer.js [hunk 3]
```diff
@@ -27,12 +51,11 @@ const createAsset = data => {
 			throw new Error(
 				'Invalid encoding in transaction data. Data must be utf-8 encoded.',
 			);
-		return { data };
 	}
-	return {};
 };
 
 const transfer = ({ amount, recipientId, recipientPublicKey, data }) => {
+	validateInputs({ amount, recipientId, recipientPublicKey, data });
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: Prefer something like this (also applies to other functions):
```js
const transfer = (inputs) => {
    validateInputs(inputs);
    const { amount, recipientId, recipientPublicKey, data } = inputs;
    // ...
};

File: packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js [hunk 4]
```diff
@@ -18,19 +18,7 @@ const getAddressAndPublicKeyFromRecipientData = ({
...
 	recipientPublicKey,
 }) => {
-	if (recipientId && recipientPublicKey) {
-		const addressFromPublicKey = cryptography.getAddressFromPublicKey(
-			recipientPublicKey,
-		);
-		if (recipientId === addressFromPublicKey) {
-			return { address: recipientId, publicKey: recipientPublicKey };
-		}
-		throw new Error(
```
Comment (shuse2) [inline packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js]: Shouldn't it still check the matching `address` vs `publicKey`?

File: packages/lisk-transactions/test/0_transfer.js [hunk 5]
```diff
@@ -18,13 +18,16 @@ const time = require('../src/utils/time');
...
 	const fixedPoint = 10 ** 8;
-	const recipientId = '58191285901858109L';
 	const testData = 'data';
 	const passphrase = 'secret';
 	const secondPassphrase = 'second secret';
 	const transactionType = 0;
 	const publicKey =
 		'5d036a858ce89f844491762eb89e2bfbd50a4a0a0da658e4b2628b25b117ae09';
+	const recipientId = '18160565574430594874L';
+	// const recipientPublicKey = '5d036a858ce89f844491762eb89e2bfbd50a4a0a0da658e4b2628b25b117ae09';
```
Comment (shuse2) [inline packages/lisk-transactions/test/0_transfer.js]: Why comment out?

File: packages/lisk-transactions/src/0_transfer.js [hunk 6]
```diff
@@ -12,13 +12,37 @@
...
 } from './utils';
 
 const createAsset = data => {
+	if (data && data.length > 0) {
+		return { data };
+	}
+	return {};
+};
+
+const validateInputs = ({ amount, recipientId, recipientPublicKey, data }) => {
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: This function should also validate the format of `recipientId` and `recipientPublicKey`.

File: packages/lisk-transactions/src/0_transfer.js [hunk 7]
```diff
@@ -27,12 +51,11 @@ const createAsset = data => {
 			throw new Error(
 				'Invalid encoding in transaction data. Data must be utf-8 encoded.',
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: I'm not actually confident we should enforce UTF8.

File: packages/lisk-transactions/src/4_register_multisignature_account.js (hunk 2 above)
Comment (willclarktech) [inline packages/lisk-transactions/src/4_register_multisignature_account.js]: Should also check if it's larger than the keysgroup length.

File: packages/lisk-transactions/src/4_register_multisignature_account.js [hunk 8]
```diff
@@ -17,11 +17,28 @@ import {
...
+		throw new Error(
+			'Please provide a valid minimum value. Expected integer between 1 and 15.',
```
Comment (willclarktech) [inline packages/lisk-transactions/src/4_register_multisignature_account.js]: This message will need to be updated too.

File: packages/lisk-transactions/src/5_create_dapp.js [hunk 9]
```diff
@@ -38,7 +38,7 @@ const validateOptions = options => {
 };
```
Comment (willclarktech) [inline packages/lisk-transactions/src/5_create_dapp.js]: We should probably also have minimal checks for the other properties.

File: packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js [hunk 10]
```diff
@@ -18,19 +18,7 @@ const getAddressAndPublicKeyFromRecipientData = ({
 	recipientId,
 	recipientPublicKey,
 }) => {
```
Comment (willclarktech) [inline packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js]: I don't think this function adds much value anymore. Can we remove it?

File: packages/lisk-transactions/src/utils/validation/validation.js [hunk 11]
```diff
@@ -86,3 +86,9 @@ export const isNumberString = str => {
 	}
 	return /^[0-9]+$/g.test(str);
 };
+
+export const validateAmount = data =>
+	isNumberString(data) && !isGreaterThanMaxTransactionAmount(bignum(data));
+
+export const isValidInteger = num =>
+	typeof num === 'number' && parseInt(num, 10) === num;
```
Comment (willclarktech) [inline packages/lisk-transactions/src/utils/validation/validation.js]: Is the `typeof` check necessary?

File: packages/lisk-transactions/test/0_transfer.js [hunk 12]
```diff
@@ -220,6 +223,26 @@ describe('#transfer transaction', () => {
...
 
+			it('should throw error when invalid amount provided', () => {
+				return expect(
+					transfer.bind(null, {
+						amount: '18446744073709551616',
+					}),
+				).to.throw('Please enter a valid amount!');
+			});
+
+			it('should throw error when recipientId & non-matching publicKey provided', () => {
```
Comment (willclarktech) [inline packages/lisk-transactions/test/0_transfer.js]: Either `recipientPublicKey` or `public key`.

File: packages/lisk-transactions/test/1_register_second_passphrase.js [hunk 13]
```diff
@@ -181,6 +181,18 @@ describe('#registerSecondPassphrase transaction', () => {
...
+			it('should throw error when secondPassphrase was not provided', () => {
+				return expect(registerSecondPassphrase.bind(null, {})).to.throw(
+					'Please provide a secondPassphrase. Expected string.',
+				);
+			});
+
+			it('should not throw error when secondPassphrase is empty string', () => {
+				return expect(
+					registerSecondPassphrase.bind(null, { secondPassphrase: '' }),
+				).to.not.throw('Please provide a secondPassphrase. Expected string.');
```
Comment (willclarktech) [inline packages/lisk-transactions/test/1_register_second_passphrase.js]: `.not.to.throw()`: no need to check the message.

File: packages/lisk-transactions/test/4_register_multisignature_account.js [hunk 14]
```diff
@@ -312,6 +312,111 @@ describe('#registerMultisignatureAccount transaction', () => {
 				return Promise.resolve();
 			});
 
+			describe('shoud throw error', () => {
```
Comment (willclarktech) [inline packages/lisk-transactions/test/4_register_multisignature_account.js]: `validation errors`: This is a suite description, but `should` implies a test.

File: packages/lisk-transactions/test/4_register_multisignature_account.js [hunk 15]
```diff
@@ -312,6 +312,111 @@ describe('#registerMultisignatureAccount transaction', () => {
...
+				describe('when #lifetime', () => {
```
Comment (willclarktech) [inline packages/lisk-transactions/test/4_register_multisignature_account.js]: `#` is used fairly inconsistently, but generally indicates a function or method under test. This should just be `lifetime`.

File: packages/lisk-transactions/test/4_register_multisignature_account.js [hunk 16]
```diff
@@ -312,6 +312,111 @@ describe('#registerMultisignatureAccount transaction', () => {
...
+							registerMultisignatureAccount.bind(null, {
+								keysgroup,
+								lifetime: -1,
+							}),
+						).to.throw(lifetimeErrorMessage);
+					});
+				});
+			});
+
+			describe('when #minimum', () => {
```
Comment (willclarktech) [inline packages/lisk-transactions/test/4_register_multisignature_account.js]: As above.

File: packages/lisk-transactions/src/0_transfer.js [hunk 17]
```diff
@@ -12,13 +12,37 @@
...
+	}
+	return {};
+};
+
+const validateInputs = ({ amount, recipientId, recipientPublicKey, data }) => {
+	if (!validateAmount(amount)) {
+		throw new Error('Please enter a valid amount!');
+	}
+
+	if (recipientId && recipientPublicKey) {
```
[the remark this answers is not in the document]
Comment (yatki) [reply packages/lisk-transactions/src/0_transfer.js]: @shuse2 I don't think so. This case only covers the situation publicKey and recipientId don't match. if only recipientId is provided then it can go to transaction and when we broadcast get an error message from network if there is any error with it. 

In the schema recipientId was only defined as a string. If there is a unique pattern I can validate but right now I think this is fine ?

[the remark this answers is not in the document]
Comment (shuse2) [reply packages/lisk-transactions/src/0_transfer.js]: Reason why `recipientId` is defined in base Transaction is that it is required, but depending on the type of transaction the requirement defers.
For type `0`, it's defined as `format: address`, but in other cases, it is empty string.

But here, I think it should check if the `recipientId` exists.

File: packages/lisk-transactions/src/0_transfer.js (hunk 7 above)
Comment (yatki) [reply packages/lisk-transactions/src/0_transfer.js]: @shuse2 could you please let me know what do you think on this? I have no idea :D

File: packages/lisk-transactions/src/utils/validation/validation.js (hunk 11 above)
Comment (yatki) [reply packages/lisk-transactions/src/utils/validation/validation.js]: If the num is undefined then parseInt is throwing exception. So I think we need it. Also proper polyfill is here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#Polyfill

File: packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js (hunk 10 above)
Comment (yatki) [reply packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js]: @willclarktech we are still using it in type o transactions.

Comment (yatki) [reply packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js]: @willclarktech are you suggesting to use `cryptography.getAddressFromPublicKey` directly in the tx function ?

Comment (willclarktech) [reply packages/lisk-transactions/src/utils/get_address_and_public_key_from_recipient_data.js]: Yes.

File: packages/lisk-transactions/src/5_create_dapp.js (hunk 9 above)
Comment (yatki) [reply packages/lisk-transactions/src/5_create_dapp.js]: @willclarktech Are they optional keys and we already have schema check. Is it really necessary ?

File: packages/lisk-transactions/src/0_transfer.js (hunk 7 above)
Comment (yatki) [reply packages/lisk-transactions/src/0_transfer.js]: @shuse2 @willclarktech could you elaborate this?

File: packages/lisk-transactions/src/0_transfer.js [hunk 18]
```diff
@@ -12,13 +12,48 @@
...
+	if (data && data.length > 0) {
+		return { data };
+	}
+	return {};
+};
+
+const validateInputs = ({ amount, recipientId, recipientPublicKey, data }) => {
+	if (!validateAmount(amount)) {
+		throw new Error(
+			'Please provide an amount. Expected a valid number in string format!',
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: `!` -> `.`

File: packages/lisk-transactions/src/2_register_delegate.js [hunk 19]
```diff
@@ -15,14 +15,31 @@
...
-	fee: DELEGATE_FEE.toString(),
-	asset: {
-		delegate: {
-			username,
+const validateInputs = ({ username }) => {
+	if (!username || typeof username !== 'string') {
+		throw new Error('Please provide a username. Expected string.');
+	}
+
+	if (username.length > 20) {
```
Comment (willclarktech) [inline packages/lisk-transactions/src/2_register_delegate.js]: This could also be moved into constants.

File: packages/lisk-transactions/src/4_register_multisignature_account.js [hunk 20]
```diff
@@ -12,16 +12,52 @@
...
+		!isValidInteger(minimum) ||
+		minimum < MULTISIGNATURE_MIN_SIGNATURES ||
+		minimum > MULTISIGNATURE_MAX_SIGNATURES
+	) {
+		throw new Error(
+			`Please provide a valid minimum value. Expected integer between ${MULTISIGNATURE_MIN_SIGNATURES} and ${MULTISIGNATURE_MAX_SIGNATURES}.`,
+		);
+	}
+
+	if (keysgroup.length < minimum) {
```
Comment (willclarktech) [inline packages/lisk-transactions/src/4_register_multisignature_account.js]: @shuse2 This should be `keysgroup.length < minimum - 1`, right?

File: packages/lisk-transactions/src/constants.js [hunk 21]
```diff
@@ -22,6 +22,10 @@ export const SIGNATURE_FEE = 5 * FIXED_POINT;
 export const DELEGATE_FEE = 25 * FIXED_POINT;
 export const VOTE_FEE = 1 * FIXED_POINT;
 export const MULTISIGNATURE_FEE = 5 * FIXED_POINT;
+export const MULTISIGNATURE_MAX_LIFETIME = 72;
+export const MULTISIGNATURE_MIN_LIFETIME = 1;
+export const MULTISIGNATURE_MAX_SIGNATURES = 15;
```
Comment (willclarktech) [inline packages/lisk-transactions/src/constants.js]: @shuse2 Please confirm this value.

File: packages/lisk-transactions/src/utils/validation/validation.js [hunk 22]
```diff
@@ -44,8 +48,13 @@ export const validatePublicKeys = publicKeys =>
 	checkPublicKeysForDuplicates(publicKeys);
 
 export const validateKeysgroup = keysgroup => {
-	if (keysgroup.length === 0 || keysgroup.length > 16) {
-		throw new Error('Expected between 1 and 16 public keys in the keysgroup.');
+	if (
+		keysgroup.length < MULTISIGNATURE_MIN_SIGNATURES ||
+		keysgroup.length > MULTISIGNATURE_MAX_SIGNATURES
```
Comment (willclarktech) [inline packages/lisk-transactions/src/utils/validation/validation.js]: @shuse2 There's a difference between the range allowed for number of signatures and the range allowed for keysgroup length, right?

File: packages/lisk-transactions/src/0_transfer.js [hunk 23]
```diff
@@ -27,16 +62,19 @@ const createAsset = data => {
...
-const transfer = ({ amount, recipientId, recipientPublicKey, data }) => {
-	const { address, publicKey } = getAddressAndPublicKeyFromRecipientData({
-		recipientId,
-		recipientPublicKey,
-	});
+const transfer = inputs => {
+	validateInputs(inputs);
+	const { amount, recipientId, recipientPublicKey, data } = inputs;
+	let address = recipientId;
+	let publicKey = null;
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: Prefer a solution without `let`.

File: packages/lisk-transactions/src/3_cast_votes.js [hunk 24]
```diff
@@ -21,9 +21,13 @@ import {
...
 } from './utils';
 
-const castVotes = ({ passphrase, votes = [], unvotes = [] }) => {
+const validateInputs = ({ votes, unvotes }) => {
 	validatePublicKeys([...votes, ...unvotes]);
+};
 
+const castVotes = inputs => {
+	const { passphrase, votes = [], unvotes = [] } = inputs;
+	validateInputs({ votes, unvotes });
```
Comment (willclarktech) [inline packages/lisk-transactions/src/3_cast_votes.js]: Prefer a consistent approach here: `validateInputs(inputs)` followed by destructuring. (You can provide default values in the `validateInputs` function.)

File: packages/lisk-transactions/src/0_transfer.js (hunk 7 above)
Comment (willclarktech) [reply packages/lisk-transactions/src/0_transfer.js]: Issue created: https://github.com/LiskHQ/lisk-elements/issues/771

File: packages/lisk-transactions/src/5_create_dapp.js (hunk 9 above)
Comment (willclarktech) [reply packages/lisk-transactions/src/5_create_dapp.js]: If the schema check was sufficient we wouldn't need this issue at all. A thorough solution will include these keys. Feel free to create a follow-up issue if you think we should merge this first and address them separately.

File: packages/lisk-transactions/test/4_register_multisignature_account.js [hunk 25]
```diff
@@ -312,6 +312,111 @@ describe('#registerMultisignatureAccount transaction', () => {
 				return Promise.resolve();
 			});
 
+			describe('validation errors:', () => {
```
Comment (willclarktech) [inline packages/lisk-transactions/test/4_register_multisignature_account.js]: Remove `:`

File: packages/lisk-transactions/test/utils/validation/validation.js [hunk 26]
```diff
@@ -243,6 +245,12 @@ describe('validation', () => {
 		});
 	});
 
+	describe('#validateAmount', () => {
+		it('should return true when amount is a number and is not greater than MaxTransactionAmount', () => {
```
Comment (willclarktech) [inline packages/lisk-transactions/test/utils/validation/validation.js]: `maximum transaction amount`

File: packages/lisk-transactions/src/4_register_multisignature_account.js (hunk 20 above)
Comment (shuse2) [reply packages/lisk-transactions/src/4_register_multisignature_account.js]: Yes!
On the other PR, i fixed it on schema check in opposite way (but same thing)
https://github.com/LiskHQ/lisk-elements/pull/770/files#diff-bc8696a3bc628a23ff3642d6f438a7e5R37

File: packages/lisk-transactions/src/constants.js (hunk 21 above)
Comment (shuse2) [reply packages/lisk-transactions/src/constants.js]: so it should be ok
https://github.com/LiskHQ/lisk/blob/development/config/default/constants.js#L80-L92

File: packages/lisk-transactions/src/utils/validation/validation.js (hunk 22 above)
Comment (shuse2) [reply packages/lisk-transactions/src/utils/validation/validation.js]: I think `signatures` is misleading. the name should reflect `keysgroup`

File: packages/lisk-transactions/src/4_register_multisignature_account.js (hunk 20 above)
Comment (shuse2) [reply packages/lisk-transactions/src/4_register_multisignature_account.js]: https://github.com/LiskHQ/lisk/blob/development/logic/multisignature.js#L135-L136
This is correct according to the `core`

File: packages/lisk-transactions/src/0_transfer.js (hunk 6 above)
Comment (willclarktech) [reply packages/lisk-transactions/src/0_transfer.js]: Addressed.

File: packages/lisk-transactions/src/0_transfer.js [hunk 27]
```diff
@@ -12,13 +12,54 @@
...
+	if (data && data.length > 0) {
+		return { data };
+	}
+	return {};
+};
+
+const validateInputs = ({ amount, recipientId, recipientPublicKey, data }) => {
+	if (!validateAmount(amount)) {
+		throw new Error(
+			'Please provide an amount. Expected a valid number in string format.',
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: We should be consistent with the structure of our messages. How about `Could not create transaction: Amount must be a valid number in string format.`? (Also applies to the other messages.)

File: packages/lisk-transactions/src/0_transfer.js [hunk 28]
```diff
@@ -12,13 +12,54 @@
...
+
+	if (typeof recipientId !== 'undefined') {
+		validateAddress(recipientId);
+	}
+
+	if (typeof recipientPublicKey !== 'undefined') {
+		validatePublicKey(recipientPublicKey);
+	}
+
+	if (recipientId && recipientPublicKey) {
```
Comment (willclarktech) [inline packages/lisk-transactions/src/0_transfer.js]: We could make this a bit more succinct:
```js
if (recipientId && recipientPublicKey && recipientId !== getAddressFromPublicKey(recipientPublicKey)) {
    throw new Error('...');
}
```

File: packages/lisk-transactions/src/2_register_delegate.js [hunk 29]
```diff
@@ -12,17 +12,34 @@
...
-		delegate: {
-			username,
+const validateInputs = ({ username }) => {
+	if (!username || typeof username !== 'string') {
+		throw new Error('Please provide a username. Expected string.');
+	}
+
+	if (username.length > USERNAME_LENGTH) {
+		throw new Error(
+			`Username length does not match requirements. Expected to be less than ${USERNAME_LENGTH} characters.`,
```
Comment (willclarktech) [inline packages/lisk-transactions/src/2_register_delegate.js]: `less than` -> `no more than`

File: packages/lisk-transactions/src/3_cast_votes.js [hunk 30]
```diff
@@ -21,9 +21,30 @@ import {
...
+		publicKeys.push(...votes);
+	}
 
+	if (typeof unvotes !== 'undefined') {
+		if (!Array.isArray(unvotes)) {
+			throw new Error(
+				'Please provide a valid unvotes value. Expected an array.',
+			);
+		}
+		publicKeys.push(...unvotes);
```
Comment (willclarktech) [inline packages/lisk-transactions/src/3_cast_votes.js]: As above.

File: packages/lisk-transactions/src/3_cast_votes.js [hunk 31]
```diff
@@ -21,9 +21,30 @@ import {
...
 
-const castVotes = ({ passphrase, votes = [], unvotes = [] }) => {
-	validatePublicKeys([...votes, ...unvotes]);
+const validateInputs = ({ votes, unvotes }) => {
+	const publicKeys = [];
+	if (typeof votes !== 'undefined') {
+		if (!Array.isArray(votes)) {
+			throw new Error('Please provide a valid votes value. Expected an array.');
+		}
+		publicKeys.push(...votes);
```
Comment (willclarktech) [inline packages/lisk-transactions/src/3_cast_votes.js]: Just validate them directly here. (`.push` is as bad as `let` 😉 )

File: packages/lisk-transactions/src/4_register_multisignature_account.js [hunk 32]
```diff
@@ -12,16 +12,52 @@
...
+		minimum > MULTISIGNATURE_MAX_KEYSGROUP
+	) {
+		throw new Error(
+			`Please provide a valid minimum value. Expected integer between ${MULTISIGNATURE_MIN_KEYSGROUP} and ${MULTISIGNATURE_MAX_KEYSGROUP}.`,
+		);
+	}
+
+	if (keysgroup.length < minimum) {
+		throw new Error(
+			`Expected minimum ${minimum} public keys in the keysgroup.`,
```
Comment (willclarktech) [inline packages/lisk-transactions/src/4_register_multisignature_account.js]: This message makes an assumption about what went wrong. Something like this would be better: `Minimum number of signatures is larger than the number of keys in the keysgroup.`

File: packages/lisk-transactions/src/5_create_dapp.js [hunk 33]
```diff
@@ -35,10 +35,23 @@ const validateOptions = options => {
 	if (typeof link !== 'string') {
 		throw new Error('Dapp link must be a string.');
 	}
+
+	if (typeof description !== 'undefined' && typeof description !== 'string') {
+		throw new Error('Dapp description must be a string.');
```
Comment (willclarktech) [inline packages/lisk-transactions/src/5_create_dapp.js]: `if provided`

File: packages/lisk-transactions/src/5_create_dapp.js [hunk 34]
```diff
@@ -35,10 +35,23 @@ const validateOptions = options => {
...
+	}
+
+	if (typeof tags !== 'undefined' && typeof tags !== 'string') {
+		throw new Error('Dapp tags must be a string.');
```
Comment (willclarktech) [inline packages/lisk-transactions/src/5_create_dapp.js]: As above.

File: packages/lisk-transactions/src/5_create_dapp.js [hunk 35]
```diff
@@ -35,10 +35,23 @@ const validateOptions = options => {
...
+	}
+
+	if (typeof icon !== 'undefined' && typeof icon !== 'string') {
+		throw new Error('Dapp icon must be a string.');
```
Comment (willclarktech) [inline packages/lisk-transactions/src/5_create_dapp.js]: As above.

File: packages/lisk-transactions/src/3_cast_votes.js [hunk 36]
```diff
@@ -21,9 +21,30 @@ import {
 	wrapTransactionCreator,
 } from './utils';
 
-const castVotes = ({ passphrase, votes = [], unvotes = [] }) => {
-	validatePublicKeys([...votes, ...unvotes]);
+const validateInputs = ({ votes, unvotes }) => {
+	const publicKeys = [];
+	if (typeof votes !== 'undefined') {
+		if (!Array.isArray(votes)) {
+			throw new Error('Please provide a valid votes value. Expected an array.');
```
Comment (willclarktech) [inline packages/lisk-transactions/src/3_cast_votes.js]: `if present`

File: packages/lisk-transactions/src/3_cast_votes.js [hunk 37]
```diff
@@ -21,9 +21,30 @@ import {
...
+		}
+		publicKeys.push(...votes);
+	}
 
+	if (typeof unvotes !== 'undefined') {
+		if (!Array.isArray(unvotes)) {
+			throw new Error(
+				'Please provide a valid unvotes value. Expected an array.',
```
Comment (willclarktech) [inline packages/lisk-transactions/src/3_cast_votes.js]: `if present`

File: packages/lisk-transactions/src/constants.js [hunk 38]
```diff
@@ -22,7 +22,12 @@ export const SIGNATURE_FEE = 5 * FIXED_POINT;
 export const DELEGATE_FEE = 25 * FIXED_POINT;
 export const VOTE_FEE = 1 * FIXED_POINT;
 export const MULTISIGNATURE_FEE = 5 * FIXED_POINT;
+export const MULTISIGNATURE_MAX_LIFETIME = 72;
+export const MULTISIGNATURE_MIN_LIFETIME = 1;
+export const MULTISIGNATURE_MAX_KEYSGROUP = 15;
+export const MULTISIGNATURE_MIN_KEYSGROUP = 1;
 export const DAPP_FEE = 25 * FIXED_POINT;
+export const USERNAME_LENGTH = 20;
```
Comment (willclarktech) [inline packages/lisk-transactions/src/constants.js]: `USERNAME_MAX_LENGTH`

File: packages/lisk-transactions/src/1_register_second_passphrase.js [hunk 39]
```diff
@@ -16,7 +16,15 @@ import cryptography from 'lisk-cryptography';
 import { SIGNATURE_FEE } from './constants';
 import { wrapTransactionCreator } from './utils';
 
-const registerSecondPassphrase = ({ secondPassphrase }) => {
+const validateInputs = ({ secondPassphrase }) => {
+	if (typeof secondPassphrase !== 'string') {
+		throw new Error('Please provide a secondPassphrase. Expected string.');
```
Comment (willclarktech) [inline packages/lisk-transactions/src/1_register_second_passphrase.js]: Should we prefix every such error message with `Could not create transaction: `? It would be more consistent.

Comment (yatki) [reply packages/lisk-transactions/src/1_register_second_passphrase.js]: @willclarktech actually only transfer tx creator has `Could not create transaction: `. All the other error messages don't have this prefix. I'd prefer to remove it since we will get it during transfer creation anyway.
