### PR TITLE
Use React Native/Android-compatible buffer reverse function - Closes #710

### LINKED ISSUE #710: Android doesn't behave with instances of Buffer like instances of Array
### Expected behavior
Lisk Element should work in Android environment seamlessly.

### Actual behavior
Since the variables of type Buffer are not instances of Array, they don't have methods like `reverse` or `slice`. Major browsers add these methods to the interface by default but this is not the case for Android. 
The same issue has been brought up in [some other projects](https://github.com/Airbitz/react-native-fast-crypto/issues/4) too.

### Steps to reproduce
Try running Lisk element in a simple RN application in the Android environment. it should throw errors similar to this
screenshot_1531237325

### Which version(s) does this affect? (Environment, OS, etc...)
OS: Android
Environment: React Native
Version:

### PR DESCRIPTION
**Pull request by willclarktech**
### What was the problem?

Using `.reverse` on buffers isn't supported in the React Native/Android environment.

### How did I fix it?

Used a library which will implement reverse for buffers.

### How to test it?

Try to use `getFirstEightBytesReversed` in particular (plus other functions) in React Native/Android.

### Review checklist

* The PR solves #710 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the
	[commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-cryptography/src/convert.js [hunk 1]
```diff
@@ -14,6 +14,7 @@
  */
 import querystring from 'querystring';
 import bignum from 'browserify-bignum';
+import reverse from 'buffer-reverse';
```
Comment (yatki) [inline packages/lisk-cryptography/src/convert.js]: I think we should be a bit more clear on function names, so I suggest to change this to be `bufferReverse`.

**Comment by willclarktech** [comment]
Waiting for feedback from @reyraa

**Comment by reyraa** [comment]
@willclarktech This addresses the issue. Thank you
